/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// SPIM_1_SCLK address and mask defines
#pragma	ioport	SPIM_1_SCLK_Data_ADDR:	0x0
BYTE			SPIM_1_SCLK_Data_ADDR;
#pragma	ioport	SPIM_1_SCLK_DriveMode_0_ADDR:	0x100
BYTE			SPIM_1_SCLK_DriveMode_0_ADDR;
#pragma	ioport	SPIM_1_SCLK_DriveMode_1_ADDR:	0x101
BYTE			SPIM_1_SCLK_DriveMode_1_ADDR;
#pragma	ioport	SPIM_1_SCLK_DriveMode_2_ADDR:	0x3
BYTE			SPIM_1_SCLK_DriveMode_2_ADDR;
#pragma	ioport	SPIM_1_SCLK_GlobalSelect_ADDR:	0x2
BYTE			SPIM_1_SCLK_GlobalSelect_ADDR;
#pragma	ioport	SPIM_1_SCLK_IntCtrl_0_ADDR:	0x102
BYTE			SPIM_1_SCLK_IntCtrl_0_ADDR;
#pragma	ioport	SPIM_1_SCLK_IntCtrl_1_ADDR:	0x103
BYTE			SPIM_1_SCLK_IntCtrl_1_ADDR;
#pragma	ioport	SPIM_1_SCLK_IntEn_ADDR:	0x1
BYTE			SPIM_1_SCLK_IntEn_ADDR;
#define SPIM_1_SCLK_MASK 0x8
// MISO_SPIM_1 address and mask defines
#pragma	ioport	MISO_SPIM_1_Data_ADDR:	0x0
BYTE			MISO_SPIM_1_Data_ADDR;
#pragma	ioport	MISO_SPIM_1_DriveMode_0_ADDR:	0x100
BYTE			MISO_SPIM_1_DriveMode_0_ADDR;
#pragma	ioport	MISO_SPIM_1_DriveMode_1_ADDR:	0x101
BYTE			MISO_SPIM_1_DriveMode_1_ADDR;
#pragma	ioport	MISO_SPIM_1_DriveMode_2_ADDR:	0x3
BYTE			MISO_SPIM_1_DriveMode_2_ADDR;
#pragma	ioport	MISO_SPIM_1_GlobalSelect_ADDR:	0x2
BYTE			MISO_SPIM_1_GlobalSelect_ADDR;
#pragma	ioport	MISO_SPIM_1_IntCtrl_0_ADDR:	0x102
BYTE			MISO_SPIM_1_IntCtrl_0_ADDR;
#pragma	ioport	MISO_SPIM_1_IntCtrl_1_ADDR:	0x103
BYTE			MISO_SPIM_1_IntCtrl_1_ADDR;
#pragma	ioport	MISO_SPIM_1_IntEn_ADDR:	0x1
BYTE			MISO_SPIM_1_IntEn_ADDR;
#define MISO_SPIM_1_MASK 0x10
// LED1_PWM_CMP address and mask defines
#pragma	ioport	LED1_PWM_CMP_Data_ADDR:	0x0
BYTE			LED1_PWM_CMP_Data_ADDR;
#pragma	ioport	LED1_PWM_CMP_DriveMode_0_ADDR:	0x100
BYTE			LED1_PWM_CMP_DriveMode_0_ADDR;
#pragma	ioport	LED1_PWM_CMP_DriveMode_1_ADDR:	0x101
BYTE			LED1_PWM_CMP_DriveMode_1_ADDR;
#pragma	ioport	LED1_PWM_CMP_DriveMode_2_ADDR:	0x3
BYTE			LED1_PWM_CMP_DriveMode_2_ADDR;
#pragma	ioport	LED1_PWM_CMP_GlobalSelect_ADDR:	0x2
BYTE			LED1_PWM_CMP_GlobalSelect_ADDR;
#pragma	ioport	LED1_PWM_CMP_IntCtrl_0_ADDR:	0x102
BYTE			LED1_PWM_CMP_IntCtrl_0_ADDR;
#pragma	ioport	LED1_PWM_CMP_IntCtrl_1_ADDR:	0x103
BYTE			LED1_PWM_CMP_IntCtrl_1_ADDR;
#pragma	ioport	LED1_PWM_CMP_IntEn_ADDR:	0x1
BYTE			LED1_PWM_CMP_IntEn_ADDR;
#define LED1_PWM_CMP_MASK 0x20
// UART_1_RX address and mask defines
#pragma	ioport	UART_1_RX_Data_ADDR:	0x0
BYTE			UART_1_RX_Data_ADDR;
#pragma	ioport	UART_1_RX_DriveMode_0_ADDR:	0x100
BYTE			UART_1_RX_DriveMode_0_ADDR;
#pragma	ioport	UART_1_RX_DriveMode_1_ADDR:	0x101
BYTE			UART_1_RX_DriveMode_1_ADDR;
#pragma	ioport	UART_1_RX_DriveMode_2_ADDR:	0x3
BYTE			UART_1_RX_DriveMode_2_ADDR;
#pragma	ioport	UART_1_RX_GlobalSelect_ADDR:	0x2
BYTE			UART_1_RX_GlobalSelect_ADDR;
#pragma	ioport	UART_1_RX_IntCtrl_0_ADDR:	0x102
BYTE			UART_1_RX_IntCtrl_0_ADDR;
#pragma	ioport	UART_1_RX_IntCtrl_1_ADDR:	0x103
BYTE			UART_1_RX_IntCtrl_1_ADDR;
#pragma	ioport	UART_1_RX_IntEn_ADDR:	0x1
BYTE			UART_1_RX_IntEn_ADDR;
#define UART_1_RX_MASK 0x40
// UART_1_TX address and mask defines
#pragma	ioport	UART_1_TX_Data_ADDR:	0x0
BYTE			UART_1_TX_Data_ADDR;
#pragma	ioport	UART_1_TX_DriveMode_0_ADDR:	0x100
BYTE			UART_1_TX_DriveMode_0_ADDR;
#pragma	ioport	UART_1_TX_DriveMode_1_ADDR:	0x101
BYTE			UART_1_TX_DriveMode_1_ADDR;
#pragma	ioport	UART_1_TX_DriveMode_2_ADDR:	0x3
BYTE			UART_1_TX_DriveMode_2_ADDR;
#pragma	ioport	UART_1_TX_GlobalSelect_ADDR:	0x2
BYTE			UART_1_TX_GlobalSelect_ADDR;
#pragma	ioport	UART_1_TX_IntCtrl_0_ADDR:	0x102
BYTE			UART_1_TX_IntCtrl_0_ADDR;
#pragma	ioport	UART_1_TX_IntCtrl_1_ADDR:	0x103
BYTE			UART_1_TX_IntCtrl_1_ADDR;
#pragma	ioport	UART_1_TX_IntEn_ADDR:	0x1
BYTE			UART_1_TX_IntEn_ADDR;
#define UART_1_TX_MASK 0x80
// LED_1Pin address and mask defines
#pragma	ioport	LED_1Pin_Data_ADDR:	0x4
BYTE			LED_1Pin_Data_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_1Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_1Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_1Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_1Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_1Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_1Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_1Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_1Pin_IntEn_ADDR:	0x5
BYTE			LED_1Pin_IntEn_ADDR;
#define LED_1Pin_MASK 0x1
// LED_1Pin Shadow defines
//   LED_1Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_1Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// SPIM_2_SCLK address and mask defines
#pragma	ioport	SPIM_2_SCLK_Data_ADDR:	0x4
BYTE			SPIM_2_SCLK_Data_ADDR;
#pragma	ioport	SPIM_2_SCLK_DriveMode_0_ADDR:	0x104
BYTE			SPIM_2_SCLK_DriveMode_0_ADDR;
#pragma	ioport	SPIM_2_SCLK_DriveMode_1_ADDR:	0x105
BYTE			SPIM_2_SCLK_DriveMode_1_ADDR;
#pragma	ioport	SPIM_2_SCLK_DriveMode_2_ADDR:	0x7
BYTE			SPIM_2_SCLK_DriveMode_2_ADDR;
#pragma	ioport	SPIM_2_SCLK_GlobalSelect_ADDR:	0x6
BYTE			SPIM_2_SCLK_GlobalSelect_ADDR;
#pragma	ioport	SPIM_2_SCLK_IntCtrl_0_ADDR:	0x106
BYTE			SPIM_2_SCLK_IntCtrl_0_ADDR;
#pragma	ioport	SPIM_2_SCLK_IntCtrl_1_ADDR:	0x107
BYTE			SPIM_2_SCLK_IntCtrl_1_ADDR;
#pragma	ioport	SPIM_2_SCLK_IntEn_ADDR:	0x5
BYTE			SPIM_2_SCLK_IntEn_ADDR;
#define SPIM_2_SCLK_MASK 0x8
// SPIM_2_SCLK Shadow defines
//   SPIM_2_SCLK_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define SPIM_2_SCLK_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// MISO_SPIM_2 address and mask defines
#pragma	ioport	MISO_SPIM_2_Data_ADDR:	0x4
BYTE			MISO_SPIM_2_Data_ADDR;
#pragma	ioport	MISO_SPIM_2_DriveMode_0_ADDR:	0x104
BYTE			MISO_SPIM_2_DriveMode_0_ADDR;
#pragma	ioport	MISO_SPIM_2_DriveMode_1_ADDR:	0x105
BYTE			MISO_SPIM_2_DriveMode_1_ADDR;
#pragma	ioport	MISO_SPIM_2_DriveMode_2_ADDR:	0x7
BYTE			MISO_SPIM_2_DriveMode_2_ADDR;
#pragma	ioport	MISO_SPIM_2_GlobalSelect_ADDR:	0x6
BYTE			MISO_SPIM_2_GlobalSelect_ADDR;
#pragma	ioport	MISO_SPIM_2_IntCtrl_0_ADDR:	0x106
BYTE			MISO_SPIM_2_IntCtrl_0_ADDR;
#pragma	ioport	MISO_SPIM_2_IntCtrl_1_ADDR:	0x107
BYTE			MISO_SPIM_2_IntCtrl_1_ADDR;
#pragma	ioport	MISO_SPIM_2_IntEn_ADDR:	0x5
BYTE			MISO_SPIM_2_IntEn_ADDR;
#define MISO_SPIM_2_MASK 0x10
// MISO_SPIM_2 Shadow defines
//   MISO_SPIM_2_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define MISO_SPIM_2_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// SPIM_2_MOSI address and mask defines
#pragma	ioport	SPIM_2_MOSI_Data_ADDR:	0x4
BYTE			SPIM_2_MOSI_Data_ADDR;
#pragma	ioport	SPIM_2_MOSI_DriveMode_0_ADDR:	0x104
BYTE			SPIM_2_MOSI_DriveMode_0_ADDR;
#pragma	ioport	SPIM_2_MOSI_DriveMode_1_ADDR:	0x105
BYTE			SPIM_2_MOSI_DriveMode_1_ADDR;
#pragma	ioport	SPIM_2_MOSI_DriveMode_2_ADDR:	0x7
BYTE			SPIM_2_MOSI_DriveMode_2_ADDR;
#pragma	ioport	SPIM_2_MOSI_GlobalSelect_ADDR:	0x6
BYTE			SPIM_2_MOSI_GlobalSelect_ADDR;
#pragma	ioport	SPIM_2_MOSI_IntCtrl_0_ADDR:	0x106
BYTE			SPIM_2_MOSI_IntCtrl_0_ADDR;
#pragma	ioport	SPIM_2_MOSI_IntCtrl_1_ADDR:	0x107
BYTE			SPIM_2_MOSI_IntCtrl_1_ADDR;
#pragma	ioport	SPIM_2_MOSI_IntEn_ADDR:	0x5
BYTE			SPIM_2_MOSI_IntEn_ADDR;
#define SPIM_2_MOSI_MASK 0x20
// SPIM_2_MOSI Shadow defines
//   SPIM_2_MOSI_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define SPIM_2_MOSI_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// SPIM_1_MOSI address and mask defines
#pragma	ioport	SPIM_1_MOSI_Data_ADDR:	0x4
BYTE			SPIM_1_MOSI_Data_ADDR;
#pragma	ioport	SPIM_1_MOSI_DriveMode_0_ADDR:	0x104
BYTE			SPIM_1_MOSI_DriveMode_0_ADDR;
#pragma	ioport	SPIM_1_MOSI_DriveMode_1_ADDR:	0x105
BYTE			SPIM_1_MOSI_DriveMode_1_ADDR;
#pragma	ioport	SPIM_1_MOSI_DriveMode_2_ADDR:	0x7
BYTE			SPIM_1_MOSI_DriveMode_2_ADDR;
#pragma	ioport	SPIM_1_MOSI_GlobalSelect_ADDR:	0x6
BYTE			SPIM_1_MOSI_GlobalSelect_ADDR;
#pragma	ioport	SPIM_1_MOSI_IntCtrl_0_ADDR:	0x106
BYTE			SPIM_1_MOSI_IntCtrl_0_ADDR;
#pragma	ioport	SPIM_1_MOSI_IntCtrl_1_ADDR:	0x107
BYTE			SPIM_1_MOSI_IntCtrl_1_ADDR;
#pragma	ioport	SPIM_1_MOSI_IntEn_ADDR:	0x5
BYTE			SPIM_1_MOSI_IntEn_ADDR;
#define SPIM_1_MOSI_MASK 0x40
// SPIM_1_MOSI Shadow defines
//   SPIM_1_MOSI_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define SPIM_1_MOSI_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED2_PWM_CMP address and mask defines
#pragma	ioport	LED2_PWM_CMP_Data_ADDR:	0x4
BYTE			LED2_PWM_CMP_Data_ADDR;
#pragma	ioport	LED2_PWM_CMP_DriveMode_0_ADDR:	0x104
BYTE			LED2_PWM_CMP_DriveMode_0_ADDR;
#pragma	ioport	LED2_PWM_CMP_DriveMode_1_ADDR:	0x105
BYTE			LED2_PWM_CMP_DriveMode_1_ADDR;
#pragma	ioport	LED2_PWM_CMP_DriveMode_2_ADDR:	0x7
BYTE			LED2_PWM_CMP_DriveMode_2_ADDR;
#pragma	ioport	LED2_PWM_CMP_GlobalSelect_ADDR:	0x6
BYTE			LED2_PWM_CMP_GlobalSelect_ADDR;
#pragma	ioport	LED2_PWM_CMP_IntCtrl_0_ADDR:	0x106
BYTE			LED2_PWM_CMP_IntCtrl_0_ADDR;
#pragma	ioport	LED2_PWM_CMP_IntCtrl_1_ADDR:	0x107
BYTE			LED2_PWM_CMP_IntCtrl_1_ADDR;
#pragma	ioport	LED2_PWM_CMP_IntEn_ADDR:	0x5
BYTE			LED2_PWM_CMP_IntEn_ADDR;
#define LED2_PWM_CMP_MASK 0x80
// LED2_PWM_CMP Shadow defines
//   LED2_PWM_CMP_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED2_PWM_CMP_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LCD_1D4 address and mask defines
#pragma	ioport	LCD_1D4_Data_ADDR:	0x8
BYTE			LCD_1D4_Data_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_0_ADDR:	0x108
BYTE			LCD_1D4_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_1_ADDR:	0x109
BYTE			LCD_1D4_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_2_ADDR:	0xb
BYTE			LCD_1D4_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D4_GlobalSelect_ADDR:	0xa
BYTE			LCD_1D4_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D4_IntCtrl_0_ADDR:	0x10a
BYTE			LCD_1D4_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D4_IntCtrl_1_ADDR:	0x10b
BYTE			LCD_1D4_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D4_IntEn_ADDR:	0x9
BYTE			LCD_1D4_IntEn_ADDR;
#define LCD_1D4_MASK 0x1
// LCD_1D4 Shadow defines
//   LCD_1D4_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCD_1D4_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCD_1D4_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCD_1D4_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCD_1D4_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCD_1D4_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCD_1D5 address and mask defines
#pragma	ioport	LCD_1D5_Data_ADDR:	0x8
BYTE			LCD_1D5_Data_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_0_ADDR:	0x108
BYTE			LCD_1D5_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_1_ADDR:	0x109
BYTE			LCD_1D5_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_2_ADDR:	0xb
BYTE			LCD_1D5_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D5_GlobalSelect_ADDR:	0xa
BYTE			LCD_1D5_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D5_IntCtrl_0_ADDR:	0x10a
BYTE			LCD_1D5_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D5_IntCtrl_1_ADDR:	0x10b
BYTE			LCD_1D5_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D5_IntEn_ADDR:	0x9
BYTE			LCD_1D5_IntEn_ADDR;
#define LCD_1D5_MASK 0x2
// LCD_1D5 Shadow defines
//   LCD_1D5_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCD_1D5_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCD_1D5_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCD_1D5_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCD_1D5_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCD_1D5_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCD_1D6 address and mask defines
#pragma	ioport	LCD_1D6_Data_ADDR:	0x8
BYTE			LCD_1D6_Data_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_0_ADDR:	0x108
BYTE			LCD_1D6_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_1_ADDR:	0x109
BYTE			LCD_1D6_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_2_ADDR:	0xb
BYTE			LCD_1D6_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D6_GlobalSelect_ADDR:	0xa
BYTE			LCD_1D6_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D6_IntCtrl_0_ADDR:	0x10a
BYTE			LCD_1D6_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D6_IntCtrl_1_ADDR:	0x10b
BYTE			LCD_1D6_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D6_IntEn_ADDR:	0x9
BYTE			LCD_1D6_IntEn_ADDR;
#define LCD_1D6_MASK 0x4
// LCD_1D6 Shadow defines
//   LCD_1D6_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCD_1D6_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCD_1D6_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCD_1D6_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCD_1D6_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCD_1D6_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCD_1D7 address and mask defines
#pragma	ioport	LCD_1D7_Data_ADDR:	0x8
BYTE			LCD_1D7_Data_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_0_ADDR:	0x108
BYTE			LCD_1D7_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_1_ADDR:	0x109
BYTE			LCD_1D7_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_2_ADDR:	0xb
BYTE			LCD_1D7_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D7_GlobalSelect_ADDR:	0xa
BYTE			LCD_1D7_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D7_IntCtrl_0_ADDR:	0x10a
BYTE			LCD_1D7_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D7_IntCtrl_1_ADDR:	0x10b
BYTE			LCD_1D7_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D7_IntEn_ADDR:	0x9
BYTE			LCD_1D7_IntEn_ADDR;
#define LCD_1D7_MASK 0x8
// LCD_1D7 Shadow defines
//   LCD_1D7_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCD_1D7_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCD_1D7_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCD_1D7_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCD_1D7_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCD_1D7_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCD_1E address and mask defines
#pragma	ioport	LCD_1E_Data_ADDR:	0x8
BYTE			LCD_1E_Data_ADDR;
#pragma	ioport	LCD_1E_DriveMode_0_ADDR:	0x108
BYTE			LCD_1E_DriveMode_0_ADDR;
#pragma	ioport	LCD_1E_DriveMode_1_ADDR:	0x109
BYTE			LCD_1E_DriveMode_1_ADDR;
#pragma	ioport	LCD_1E_DriveMode_2_ADDR:	0xb
BYTE			LCD_1E_DriveMode_2_ADDR;
#pragma	ioport	LCD_1E_GlobalSelect_ADDR:	0xa
BYTE			LCD_1E_GlobalSelect_ADDR;
#pragma	ioport	LCD_1E_IntCtrl_0_ADDR:	0x10a
BYTE			LCD_1E_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1E_IntCtrl_1_ADDR:	0x10b
BYTE			LCD_1E_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1E_IntEn_ADDR:	0x9
BYTE			LCD_1E_IntEn_ADDR;
#define LCD_1E_MASK 0x10
// LCD_1E Shadow defines
//   LCD_1E_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCD_1E_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCD_1E_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCD_1E_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCD_1E_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCD_1E_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCD_1RS address and mask defines
#pragma	ioport	LCD_1RS_Data_ADDR:	0x8
BYTE			LCD_1RS_Data_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_0_ADDR:	0x108
BYTE			LCD_1RS_DriveMode_0_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_1_ADDR:	0x109
BYTE			LCD_1RS_DriveMode_1_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_2_ADDR:	0xb
BYTE			LCD_1RS_DriveMode_2_ADDR;
#pragma	ioport	LCD_1RS_GlobalSelect_ADDR:	0xa
BYTE			LCD_1RS_GlobalSelect_ADDR;
#pragma	ioport	LCD_1RS_IntCtrl_0_ADDR:	0x10a
BYTE			LCD_1RS_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1RS_IntCtrl_1_ADDR:	0x10b
BYTE			LCD_1RS_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1RS_IntEn_ADDR:	0x9
BYTE			LCD_1RS_IntEn_ADDR;
#define LCD_1RS_MASK 0x20
// LCD_1RS Shadow defines
//   LCD_1RS_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCD_1RS_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCD_1RS_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCD_1RS_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCD_1RS_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCD_1RS_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCD_1RW address and mask defines
#pragma	ioport	LCD_1RW_Data_ADDR:	0x8
BYTE			LCD_1RW_Data_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_0_ADDR:	0x108
BYTE			LCD_1RW_DriveMode_0_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_1_ADDR:	0x109
BYTE			LCD_1RW_DriveMode_1_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_2_ADDR:	0xb
BYTE			LCD_1RW_DriveMode_2_ADDR;
#pragma	ioport	LCD_1RW_GlobalSelect_ADDR:	0xa
BYTE			LCD_1RW_GlobalSelect_ADDR;
#pragma	ioport	LCD_1RW_IntCtrl_0_ADDR:	0x10a
BYTE			LCD_1RW_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1RW_IntCtrl_1_ADDR:	0x10b
BYTE			LCD_1RW_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1RW_IntEn_ADDR:	0x9
BYTE			LCD_1RW_IntEn_ADDR;
#define LCD_1RW_MASK 0x40
// LCD_1RW Shadow defines
//   LCD_1RW_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCD_1RW_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCD_1RW_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCD_1RW_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCD_1RW_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCD_1RW_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
