/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
// =============================================================================
// FILENAME: PSoCAPI.h
// 
// Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
// 
// NOTES:
// Do not modify this file. It is generated by PSoC Designer each time the
// generate application function is run. The values of the parameters in this
// file can be modified by changing the values of the global parameters in the
// device editor.
// 
// =============================================================================
 
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "LCD_1.h"
#include "LED1_PWM.h"
#include "LED2_PWM.h"
#include "LED_1.h"
#include "SPIM_1.h"
#include "SPIM_2.h"
#include "Timer32_1.h"
#include "UART_1.h"

#endif
